# .streamlit/secrets.toml

[database]
# This is the path your app will use for the SQLite file
# In Streamlit Cloud we recommend a /tmp path; locally you can override via env
path = "/tmp/lab_inventory.db"

[chronect]
# The Dropbox-synced folder on the machine that holds your new CHRONECT xlsx's
input_dir = "/Users/amd/Dropbox/ChronectOutputs"